
- name: Deploy to GitHub Pages
  uses: actions/deploy-pages@v4
  with:
    branch: gh-pages
    folder: myblog
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: myblog



permissions:
  id-token: write
  contents: write
